### ISSUE TITLE
خطا در تست مدل ترجمه ماشینی

### ISSUE THREAD

**Issue by miladfa7** [snrazavi/Deep_Learning_in_Python_2018#3]
من برنامه مربوط به ترجمه ماشینی رو اجرا کردم ولی در هنگام تست کردن این خطارو میده 
مشکل از کجاست؟

![Screenshot from 2020-05-20 13-47-11](https://user-images.githubusercontent.com/25765644/82429253-d8be0c80-9aa0-11ea-9051-42de97fd60de.png)

**Comment by snrazavi** [comment]
This errors is related to using an old pytorch version. After updating the codes, this error no longer exists. Please download the latest version to solve the issue.
