### ISSUE TITLE
ImportError

### ISSUE THREAD

**Issue by anonym2027** [snrazavi/Deep_Learning_in_Python_2018#6]
when I want to run the week01/lesson01-classification ipynb file, Although I used pip to install train,  I have the following error:
ImportError: cannot import name 'train_model' from 'train' (C:\Users\USER\anaconda3\lib\site-packages\train\__init__.py)
How can I solve it?

**Comment by snrazavi** [comment]
There is no package called "train", so you don't need to install that package. There is a train.py file in the same directory and the train_model is imported from this file.
